name: asaverse_parsers
description: Manga parsers library for Dart and Flutter
version: 1.0.1
repository: https://github.com/i4ox/asaverse_parsers.git

environment:
  sdk: ^3.5.0

# Add regular dependencies here.
dependencies:
  dio: ^5.5.0+1
  html: ^0.15.4

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
